### ISSUE TITLE
Network metadata not loading when extension is active

### ISSUE THREAD

**Issue by Cruxial0** [corbin-hayden13/SD-Lora-Tagger#20]
Whenever the extension is active, clicking the 'Edit Metadata' button on networks results in the following error

```
reading info for L_15_AhriArcana: FileNotFoundError
Traceback (most recent call last):
  File "C:\Users\user\stable-ui\modules\ui_extra_networks_user_metadata.py", line 105, in get_metadata_table
    stats = os.stat(filename)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'F:\\AI\\Models\\LoRAs\\Characters\\L_15_AhriArcana'
```
It happens for all networks except for texual inversions.

Steps to reproduce:
1. Enable the extension
2. Click the 'Edit Metadata' button on any on the aforementioned networks

---

Distribution: Automatic1111 WebUI (v1.7.0-7-gfe3a918c)

**Comment by corbin-hayden13** [comment]
Most likely an issue with the re-registration process, I'll take a look at it and try to reproduce

**Comment by corbin-hayden13** [comment]
I get the error but editing metadata still works... this is odd behavior, does editing metadata still work for you?

**Comment by corbin-hayden13** [comment]
Yup, I found the issue and fixed it, lemme create a branch and pull request
