### ISSUE TITLE
Just get error - A1111 1.8 Tree Support?

### ISSUE THREAD

**Issue by MrKuenning** [corbin-hayden13/SD-Lora-Tagger#35]
I have been looking for better ways to organize my thousands of LORAs, but I am getting a blank box with an error in the middle.
Does this support the new A1111 1.8 tree view?

**Comment by Cruxial0** [comment]
Thanks for reaching out!

I was not aware of the A1111 new release until today. The tree-view indeed seems to be the source of the issue. I'm currently looking into it.
